# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sihun Cha
name: Sihun Cha
position: Ph.D. student
email: chacorp@kaist.ac.kr
description: >-
  I am a Ph.D. student at [Visual Media Lab](https://vml.kaist.ac.kr/), [KAIST](https://www.kaist.ac.kr/en/), advised by Prof. [Junyong Noh](https://vml.kaist.ac.kr/main/people/person/1). 
  I studied Fine Arts as a Bachelor at [Korea National University of Arts](https://www.karts.ac.kr/en/main.do).
  

  'How to create and manipulate 3D content intuitively?' is my overall question. 
  My current research interest lies on generating and editing digital 3D avatar.


baseurl: "https://sihuncha.tumblr.com/" # the subpath of your site, e.g. /blog
url: "https://chacorp.github.io/sihuncha/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: chacorp
google_scholar: gwSV7H4AAAAJ
google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
